title: Мои заметки
description: Блокнот, ссылки, фото
theme: minima
baseurl: "/notes3Kf74u55e405ML"   # ВАЖНО: замените на имя вашего репозитория (например, /notes)
url: "https://gvineon550-coder.github.io" # Замените на ваш ник
