name: Compress Images

on:
  push:
    branches: [main]
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: false
          jpegQuality: '85'
          pngQuality: '80'
          webpQuality: '85'

      - name: Create Pull Request
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v5
        with:
          title: "🤖 Сжатие фото"
          branch-suffix: timestamp
          commit-message: "Сжатие"
          body: ${{ steps.calibre.outputs.markdown }}
